---
- lineinfile: dest="{{ apache.config_path }}/httpd.conf" line="{{ item }}"
  with_items:
    - "Include etc/apache24/mods-enabled/*.conf"
    - "Include etc/apache24/mods-enabled/*.load"
    - "Include etc/apache24/conf.d/*.conf"
    - "Include etc/apache24/sites-enabled/*.conf"

- template: src=module.load dest="{{ apache.config_path }}/mods-available/{{ item.load }}" owner=root group={{ root_group }}
  with_items: apache.modules

# Remove module lines from httpd.conf
- lineinfile: dest="{{ apache.config_path }}/httpd.conf" regexp="^LoadModule (.*)" state=absent

- name: "APACHE | mod_jk installation"
  pkgng: name="ap24-mod_jk" state=installed
  when: "'jk' in apache.modules"

- name: "APACHE | mod_auth_pgsql2 installation"
  pkgng: name="ap24-mod_auth_pgsql2" state=installed
  when: "'auth_pgsql2' in apache.modules"

# Add module links
- name: "APACHE | Enable modules"
  file: src={{ apache.config_path }}/mods-available/{{ item }}.load dest={{ apache.config_path }}/mods-enabled/{{ item }}.load state=link
  with_items: apache.modules
  notify: restart apache

- name: "APACHE | Blacklist modules"
  file: src={{ apache.config_path }}/mods-available/{{ item }}.load dest={{ apache.config_path }}/mods-enabled/{{ item }}.load state=absent
  with_items: apache.modules_blacklist
  notify: restart apache

