---
- name: "Apache2 | Include {{ ansible_os_family }} specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Apache2 | {{ ansible_os_family }} specific installation"
  include: "install-{{ ansible_os_family }}.yml"

- name: "Apache2 | Modules management"
  include: modules.yml

# Security
- name: "Apache2 | {{ ansible_os_family }} specific security"
  include: "security-{{ ansible_os_family }}.yml"

# Configure virtualhosts
- name: "Apache2 | Web Sites Root Directory creation"
  file: name={{ item.document_root | default('/var/www/' + item.name) }} owner={{ www_user }} group={{ www_group }} state=directory mode=0755
  with_items: "{{ apache.vhosts }}"
  when: apache.vhosts is defined

- name: "Apache2 | Virtualhost configuration"
  template: src=virtualhost.conf dest={{ apache.config_path }}/sites-available/{{ item.name }}.conf owner=root group={{ root_group }} mode=0644
  with_items: "{{ apache.vhosts }}"
  when: item.custom_template is not defined
  notify: reload apache

- name: "Apache2 | Virtualhost template deployment"
  template: src={{ item.custom_template }} dest={{ apache.config_path }}/sites-available/{{ item.name }}.conf owner=root group={{ root_group }} mode=0644
  with_items: "{{ apache.vhosts }}"
  when: item.custom_template is defined
  notify: reload apache

- name: "Apache2 | Virtualhost activation"
  file: src={{ apache.config_path }}/sites-available/{{ item.name }}.conf dest={{ apache.config_path }}/sites-enabled/{{ item.name }}.conf state=link
  with_items: "{{ apache.vhosts }}"
  notify: reload apache

# Service
- name: "Apache2 | Service state management"
  service: name={{ apache.service_name }} state=started enabled={{ apache.service_enable }}
  when: apache.service_manage
