---
- name: "Apache2 | mod_jk Installation"
  package: name="{{ apache.module_names.jk }}" state=installed
  when: "'{{ item.name }}' == 'jk' and '{{ item.state }}' == 'present' "
  with_items: "{{ apache.modules }}"
  notify: restart apache

- name: "Apache2 | mod_jk Configuration"
  template: src="mod_jk.conf" dest="{{ apache.config_path }}/mods-available/jk.conf" owner=root group={{ root_group }}
  when: "'{{ item.name }}' == 'jk' and '{{ item.state }}' == 'present' "
  with_items: "{{ apache.modules }}"
  notify: reload apache

- name: "Apache2 | mod_jk workers.properties"
  template: src="workers.properties" dest="{{ apache.config_path }}/workers.properties" owner=root group={{ root_group }}
  when: "'{{ item.name }}' == 'jk' and '{{ item.state }}' == 'present' "
  with_items: "{{ apache.modules }}"
  notify: reload apache

- name: "Apache2 | mod_auth_pgsql installation"
  package: name="{{ apache.module_names.auth_pgsql }}" state=installed
  when: "'{{ item.name }}' == 'auth_pgsql' and '{{ item.state }}' == 'present' "
  with_items: "{{ apache.modules }}"
  notify: restart apache

- name: "Apache2 | Disable Modules"
  file: path={{ apache.config_path }}/mods-enabled/jk.conf state=absent
  when: "'{{ item.name }}' == 'jk' and '{{ item.state }}' != 'present' "
  with_items: "{{ apache.modules }}"
  notify: reload apache

- name: "Apache2 | Enable required Modules"
  file: src={{ apache.config_path }}/mods-available/jk.conf dest={{ apache.config_path }}/mods-enabled/jk.conf state=link
  when: "'{{ item.name }}' == 'jk' and '{{ item.state }}' == 'present' "
  with_items: "{{ apache.modules }}"
  notify: reload apache

- name: "Apache2 | {{ ansible_os_family }} specific configuration"
  include: "modules-{{ ansible_os_family }}.yml"

